[package]
name = "happycache"
version = "0.1.0"
authors = ["Josh Snyder <josh@code406.com>"]
edition = "2021"

[dependencies]
clap = { version = "4.3.19", features = ["derive"] }
flate2 = "1.0.26"
libc = "0.2.147"
once_cell = "1.18.0"
